package com.ceimo.gestion.entity.membre;

public enum Poste {
	
	PRESIDENT,
	VICE_PRESIDENT,
	SECRETAIRE,
	SECRETAIRE_ADJOINT,
	COMMISSAIRE_AU_COMPTE_1,
	COMMISSAIRE_AU_COMPTE_2,
	TRESORIER,
	CENSEUR,
	MEMBRE
}
